import Gallery from "@/components/Gallery";
import Salon from "@/components/Salon";
import Speciality from "@/components/Specialty";
import Baths from "@/enComponents/Baths";
import Booking from "@/enComponents/Booking";
import Formules from "@/enComponents/Formules";
import Hero from "@/enComponents/Hero";
import Services from "@/enComponents/Services";
import Head from "next/head";
import React from "react";
import { client } from "../../lib/client";

export default function en({ servicesEn, formulesEn, gallery }) {
  return (
    <>
      <Head>
        <title>Hammam Ziani || English</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Baths />
        <Speciality />
        <Services servicesEn={servicesEn} />
        <Formules formulesEn={formulesEn} />
        <Salon />
        <Gallery gallery={gallery} title="gallery" />
        <Booking />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "servicesEnglish"]';
  const query2 = '*[_type == "gallery"]';
  const query3 = '*[_type == "formulesEnglish"]';
  const servicesEn = await client.fetch(query);
  const gallery = await client.fetch(query2);
  const formulesEn = await client.fetch(query3);
  return {
    props: {
      servicesEn,
      gallery,
      formulesEn,
    },
  };
};
