import Gallery from "@/components/Gallery";
import Salon from "@/components/Salon";
import Speciality from "@/components/Specialty";
import Baths from "@/enComponents/Baths";
import Booking from "@/enComponents/Booking";
import Formules from "@/enComponents/Formules";
import Hero from "@/enComponents/Hero";
import Services from "@/enComponents/Services";
import Head from "next/head";
import React from "react";

export default function en() {
  return (
    <>
      <Head>
        <title>Hammam Ziani || English</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Baths />
        <Speciality />
        <Services />
        <Formules />
        <Salon />
        <Gallery title="gallery" />
        <Booking />
      </main>
    </>
  );
}
