import Baths from "@/components/Baths";
import Booking from "@/components/Booking";
import Formules from "@/components/Formules";
import Gallery from "@/components/Gallery";
import Hero from "@/components/Hero";
import Salon from "@/components/Salon";
import Services from "@/components/Services";
import Specialty from "@/components/Specialty";
import Head from "next/head";
import { client } from "../../lib/client";
export default function Home({ services, formules, gallery }) {
  return (
    <>
      <Head>
        <title>Hammam Ziani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Hero />
        <Baths />
        <Specialty />
        <Services services={services} />
        <Formules formules={formules} />
        <Salon />
        <Gallery gallery={gallery} title="galerie" />
        <Booking />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "services"]';
  const query2 = '*[_type == "gallery"]';
  const query3 = '*[_type == "formules"]';
  const services = await client.fetch(query);
  const gallery = await client.fetch(query2);
  const formules = await client.fetch(query3);
  return {
    props: {
      services,
      gallery,
      formules,
    },
  };
};
